### ISSUE TITLE
Alcuni indirizzi hanno il geocoding a null

### ISSUE THREAD

**Issue by baldoalessandro** [xrmx/parse-medici-torino#7]
```json
{"nome": "BERTETTI MARIA TERESA", "codice": "014855R", "associazione": ["ASL TO RETE 146"], "indirizzi": [{"indirizzo": "VIA B. LUINI 131 bis TORINO 10149", "telefono": ["0114557027"], "giorni": ["Lunedi", "Martedi", "Mercoledi", "Giovedi", "Venerdi"], "ore": ["16:00", "16:00", "16:00", "14:00", "09:00", "19:00", "19:00", "19:00", "17:00", "12:00"], "note": [], "orario_affidabile": true, "orari": [{"giorno": "Lunedi", "da": "16:00", "a": "19:00"}, {"giorno": "Martedi", "da": "16:00", "a": "19:00"}, {"giorno": "Mercoledi", "da": "16:00", "a": "19:00"}, {"giorno": "Giovedi", "da": "14:00", "a": "17:00"}, {"giorno": "Venerdi", "da": "09:00", "a": "12:00"}], "posizione": null}]}```

```json
 {"nome": "BORSERO LUIGI", "codice": "010231X", "associazione": ["ASL TO RETE 78"], "indirizzi": [{"indirizzo": "VIA G. MOSCA 7 TORINO 10147", "telefono": ["3315434608"], "giorni": ["Lunedi", "Martedi", "Mercoledi", "Giovedi", "Venerdi"], "ore": ["16:30", "14:00", "11:00", "16:00", "13:00", "19:30", "16:30", "14:00", "19:00", "16:30"], "note": [], "orario_affidabile": true, "orari": [{"giorno": "Lunedi", "da": "16:30", "a": "19:30"}, {"giorno": "Martedi", "da": "14:00", "a": "16:30"}, {"giorno": "Mercoledi", "da": "11:00", "a": "14:00"}, {"giorno": "Giovedi", "da": "16:00", "a": "19:00"}, {"giorno": "Venerdi", "da": "13:00", "a": "16:30"}], "posizione": null}]}```

**Comment by xrmx** [comment]
Grazie per la segnalazione. E' perchè mapbox non li trova, conviene far tornare quelli non trovati su stderr e farsi una mappa per riscriverli prima di fare la query a mapbox.

**Comment by xrmx** [comment]
Chiesto a mapbox se abbiamo altre opzioni prima di fare la mappa https://twitter.com/rmistaken/status/1282258876272906240

**Comment by xrmx** [comment]
Tutti gli indirizzi che falliscono:

[geocoding-fallito.txt](https://github.com/xrmx/parse-medici-torino/files/4908327/geocoding-fallito.txt)

**Comment by hedoluna** [comment]
> Tutti gli indirizzi che falliscono:
> 
> [geocoding-fallito.txt](https://github.com/xrmx/parse-medici-torino/files/4908327/geocoding-fallito.txt)

Dici che si potrebbe provare ad usare un sistema di fallback per gli indirizzi?
Tipo in prima battuta provo così come lo trovo dal parsing, poi provo rimuovendo le lettere puntate (A., G., ecc), poi provo rimuovendo i "bis" e gli "int", e magari anche togliendo il CAP...

**Comment by xrmx** [comment]
@hedoluna non so, dalle prove che ho fatto mi pare che mapbox necessiti dell'indirizzo completo, quindi con la parte abbreviata esplicita ta.

**Comment by xrmx** [comment]
Sistemato in 3c0598b8710f853815d99879cd81c5ef7b1face6
